# Generated by Django 2.1 on 2018-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181022_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=60)),
                ('last', models.CharField(max_length=60)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='webapp.Flight')),
            ],
        ),
    ]
